// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Practise_project.Data;

#nullable disable

namespace Practise_project.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260716021809_New_Tables")]
    partial class New_Tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Practise_project.Data.InvoiceEntitiy", b =>
                {
                    b.Property<int>("Invoice_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Invoice_id"));

                    b.Property<int>("Create_person_id")
                        .HasColumnType("int");

                    b.Property<string>("Customer_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Entry_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Invoice_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Update_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Void_flag")
                        .HasColumnType("bit");

                    b.HasKey("Invoice_id");

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("Practise_project.Data.InvoiceItemEntitiy", b =>
                {
                    b.Property<int>("Invoice_item_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Invoice_item_id"));

                    b.Property<string>("Charge_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Cost_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Create_person_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Entry_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Invoice_id")
                        .HasColumnType("int");

                    b.Property<decimal?>("Revenue_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<short>("Rowver")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("Update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("Invoice_item_id");

                    b.ToTable("Invoice_item");
                });

            modelBuilder.Entity("Practise_project.Data.PersonEntitiy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GivenName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalLanguageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });
#pragma warning restore 612, 618
        }
    }
}
